test:
  image: "ruby:2.6.3"
  script:
    - echo "HELLO!"
  only:
    - external_pull_requests
    - develop

.credentails_template: &credentials
  before_script:
    - printf "[default]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
    - printf "[default]\nregion=us-east-1" > ~/.aws/config

deploy_review:
  <<: *credentials
  stage: deploy
  image: coxauto/aws-ebcli
  script:
    - echo "DEPLOY!"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://git-shoutout-$CI_ENVIRONMENT_SLUG.us-east-1.elasticbeanstalk.com
    on_stop: stop_review
  only:
    - external_pull_requests

stop_review:
  <<: *credentials
  stage: deploy
  image: coxauto/aws-ebcli
  script:
    - echo "Terminate!"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when:
    manual
  only:
    - external_pull_requests

deploy:
  <<: *credentials
  stage: deploy
  image: coxauto/aws-ebcli
  script:
    - echo "Deploy Staging"
  environment:
    name: staging
    url: http://git-shoutout-staging.us-east-1.elasticbeanstalk.com
  only:
    - develop
