version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.1-stretch-node
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Run Specs
          command: bundle exec rspec
  deploy_review_app:
    docker:
      - image: coxauto/aws-ebcli
    steps:
      - checkout
      - run:
          name: "Setup CI_ENVIRONMENT_SLUG environment variables"
          command: |
            echo 'export CI_ENVIRONMENT_SLUG="$CIRCLE_BRANCH$CIRCLE_SHA1"' >> $BASH_ENV
      - run:
          name: Prepare deploy script
          command: chmod +x ./deploy.sh
      - run:
          name: Deploy application
          command: ./deploy.sh

workflows:
  version: 2
  test_and_deploy_review_app:
    jobs:
      - test
      - deploy_review_app:
          requires:
            - test
